In [1]:
import numpy as np
h= np.eye(3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
i= np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
k= np.ones((3, 4))
k

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
l = np.zeros((3, 4))
l

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
l = np.zeros((6, 2))
l

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

***Transpuesta de una matriz***

In [6]:
m = np.array([[0., 5., 0., 0.],
              [0., 5., 0., 0.],
              [0., 5., 0., 0.]])
m

array([[0., 5., 0., 0.],
       [0., 5., 0., 0.],
       [0., 5., 0., 0.]])

In [7]:
m.transpose()

array([[0., 0., 0.],
       [5., 5., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
m.T

array([[0., 0., 0.],
       [5., 5., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:

np.all(m < 0)

False

In [10]:
np.any(m>2)     #Algun elemento mayor que 0

True

In [11]:
np.ravel(m)     #pone una sola dimension de una matriz

array([0., 5., 0., 0., 0., 5., 0., 0., 0., 5., 0., 0.])

In [12]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.ravel(m1)#RAVEL

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
m3 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [15]:
m3.flatten()    #lo mismo que raven pero crea copia FLATTEN

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#ROLL
np.roll(m3, 1, axis=0)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
np.roll(m3, 1, axis=1)

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [18]:
np.roll(m3, -1, axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [19]:
#LOGSPACE
#ARRAY de elementos logaritmicos espaciados

c = np.logspace(0,1,3)
c

array([ 1.        ,  3.16227766, 10.        ])

In [20]:
m3 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
m3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
m3[2][1] #fila 2 valor 1

8

In [22]:
m3[2,1]  #fila 2 valor 1

8

In [23]:
m3[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
m3[2:]

array([[7, 8, 9]])

In [25]:
m3[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
m3[0][2]

3

In [27]:
#transpuesta con bucles
m3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
madmax = np.zeros((4, 4))
madmax

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
for i in range(0, len(madmax)):
    for j in range(0, len(madmax[i])):
        if i == j:
            madmax[i][j] = 1
madmax        

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
madmax[2][2]

1.0

In [31]:
m3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
mo = np.array([[1,2,],
               [4,5,],
               [7,8,],
              ])
mo               

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
t =[]
for i in range(0, len(mo[0])):
    t.append([])
    for j in range(0, len(mo)):
        t[i][j].append(mo[j][i])
t        

IndexError: list index out of range